### ISSUE TITLE
ЧР, запуск скрипта

### ISSUE THREAD

**Issue by Clusiv** [foi/pasreg-tools#1]
Добрый день.
1)Скрипт встревает на:
анные по региону будут размещены в data/19
RangeError: Maximum call stack size exceeded
    at range (/home/imran/Downloads/pasreg-tools-master/dump.js:48:19)
    at range (/home/imran/Downloads/pasreg-tools-master/dump.js:50:25)
    at range (/home/imran/Downloads/pasreg-tools-master/dump.js:50:25)
    at range (/home/imran/Downloads/pasreg-tools-master/dump.js:50:25)
    at range (/home/imran/Downloads/pasreg-tools-master/dump.js:50:25)
    at range (/home/imran/Downloads/pasreg-tools-master/dump.js:50:25)
    at range (/home/imran/Downloads/pasreg-tools-master/dump.js:50:25)
    at range (/home/imran/Downloads/pasreg-tools-master/dump.js:50:25)
    at range (/home/imran/Downloads/pasreg-tools-master/dump.js:50:25)
    at range (/home/imran/Downloads/pasreg-tools-master/dump.js:50:25)

NodeJS 12, Ubuntu.

**Comment by foi** [comment]
Да, у меня тоже самое, скорее всего они снова изменили API.
Исправлений не гарантирую, т.к. сейчас мне заниматься этим порталом не нужно.
